name: TNP Scraper

permissions:
  contents: write

on:
  schedule:
    - cron: "30 3 * * *"
    - cron: "30 7 * * *"
    - cron: "30 14 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps chromium

      - name: Run scraper
        env:
          USERNAME_TP: ${{ secrets.USERNAME_TP }}
          PASSWORD_TP: ${{ secrets.PASSWORD_TP }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python scraper.py

      - name: Commit updated state.json
        run: |
          git add state.json

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "Update last fetched timestamp"
            git push
          fi